# Generated by Django 5.1.7 on 2025-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='doctor',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='doctor_id',
            field=models.CharField(default='unknown', max_length=42),
            preserve_default=False,
        ),
    ]
